mkdir -p .github/workflows

cat > .github/workflows/test-ssh.yml <<'EOF'
name: Test SSH to SiteGround

on:
  workflow_dispatch:   # lets you trigger manually from GitHub UI

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p ${{ secrets.DEPLOY_PORT }} -H "${{ secrets.DEPLOY_HOST }}" >> ~/.ssh/known_hosts

      - name: Test SSH connection
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
        run: |
          ssh -p "$DEPLOY_PORT" -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" "echo '✅ SSH works from GitHub Actions!'"
EOF

